#!/usr/bin/python3

def raise_exception_msg(message=""):
    """Raise a NameError_exception with_message."""
    raise NameError(message)
